apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hostname
  labels:
    app: node-hostname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hostname
  template:
    metadata:
      labels:
        app: node-hostname
    spec:
      containers:
      - name: node-hostname
        image: ghcr.io/zozs/node-hostname
        env:
        - name: PORT
          value: "3000"
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-hostname
spec:
  selector:
    app: node-hostname
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: node-hostname
spec:
  entryPoints:
  #- websecure
  - web
  routes:
  - kind: Rule
    match: Host(`hostname.cryptosec.se`)
    services:
    - name: node-hostname
      port: http
  #tls:
  #  certResolver: myresolver
---
